sudo: required
language: node_js
notifications:
  email: false
services:
  - docker
# https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-%28or-io.js-v3%29-compiler-requirements
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
node_js:
  - 4
before_install:
  - docker version
  - docker run -d -p 127.0.0.1:5984:5984 klaemo/couchdb:1.6.1
  - docker build -t hoodiehq/hoodie-app-tracker .
  - npm install --global npm@3
  - npm prune
before_script:
  # tell us what CouchDB version we have
  - curl http://localhost:5984
  # create secret (works around CouchDB racing issue)
  - curl -X PUT -d '"78875068a1979fb910d5d8f37d316aa4"' 'http://localhost:5984/_config/couch_httpd_auth/secret'
  # create admin account for testing (admin:secret)
  - curl -X PUT -d '"secret"' 'http://localhost:5984/_config/admins/admin'
  # required for headless firefox / selenium test
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
after_success:
  - npm run semantic-release
deploy:
- provider: script
  script: docker login -e $DOCKER_EMAIL -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && docker push hoodiehq/hoodie-app-tracker
  on:
    branch: master
env:
  global:
    - CXX=g++-4.8
  matrix:
    # - CLIENT=selenium:firefox
    - CLIENT=saucelabs:chrome
    # test with CouchDB (by default it tests with PouchDB)
    - hoodie_dbUrl=http://admin:secret@127.0.0.1:5984 CLIENT=saucelabs:chrome
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
